### ISSUE TITLE
Virtual meeting won't open

### ISSUE THREAD

**Issue by Elizabeth7797** [bmlt-enabled/BMLTSearch3#43]
When I click on a virtual meeting it just goes back to the search it doesn't open zoom.

**Comment by paulnagle** [comment]
Thanks for opening the ticket.. This works fine for me on my phone. What type of phone are you using? Could you let me know what part of the app you are seeing this in? i.e is it from the Map Search , or the Current Location Search, BMLT Meeting List or virtual-na.org menu item?

**Comment by paulnagle** [comment]
Double checked that this works ok for me on version 4.4.0. Please re-open the ticket if you have any more info!
