### ISSUE TITLE
CPRNA

### ISSUE THREAD

**Issue by f40t12** [bmlt-enabled/BMLTSearch3#47]

**Comment by paulnagle** [comment]
Hi, not sure if there were some more details that you wanted to provide here?

**Comment by f40t12** [comment]
Wed 8:30PM Conscious Contact Beginners (O,WC ♿, 60), Wesley UMC, Library on the lower level; plz use the Jenifer Street entrance, 5312 Connecticut Avenue NW, Wash. DC 20015Thu 7:00PM Meeting on the Avenue (O, 60), Wesley UMC, Library on lower level; plz use the Jenifer Street entrance, 5312 Connecticut Avenue              NW, Washington, DC, 20015Eric Epstein3003 Van Ness St NW333WWashington, DC ***@***.*** A. Epstein 3003 Van Ness St NWApt.# W333Washington, DC ***@***.*** Sep 10, 2023, at 4:05 AM, Paul Nagle ***@***.***> wrote:﻿
Hi, not sure if there were some more details that you wanted to provide here?

**Comment by paulnagle** [comment]
Sorry dude, I still have no idea what you need. The repository is for the source code of the BMLT Search app. If you need to update a meeting, you should contact your local BMLT admin person.

**Comment by chapmangeo** [comment]
I have no idea how this got opened on my ID.  I certainly never opened this issue.
