### ISSUE TITLE
Tejas Bluebonnet Region is not an option

### ISSUE THREAD

**Issue by chapmangeo** [bmlt-enabled/BMLTSearch3#49]
Location search (Map) finds TBRNA (Central Texas Area) both of which are on BMLT.  But the  "BMLT MEETING LIST" menu option offers neither.

**Comment by jbraswell** [comment]
It's under Southern Zonal Forum.

**Comment by chapmangeo** [comment]
Ah, thanks for that.  It should have occurred to me.  

I might suggest that if, as an experienced user (I'm CTANA's IT Services coordinator) I missed it, that might be a level of aggretization that a newcomer would also find confusing...

**Comment by jbraswell** [comment]
Service bodies host their own root servers. Some are zones, some are regions. Some assign a parent zonal body, some don't. There are a few dozen root servers in the world. You can see them all at tally.bmlt.app.

We have an aggregator that downloads all of their data every few hours, and serves it up from one giant root server.

This app uses that aggregator.

So, it's just a mirror of the data in each root server.

This isn't necessarily to justify the current behavior. Just to explain what is happening.

Agreed there's probably a better way to present the data. Maybe the app just shouldn't show zones in the list at all?

But, I'd argue your typical meeting goer will only use a location search. Most don't seem to understand or care about the service structure - they simply want to find a meeting near them.

**Comment by chapmangeo** [comment]
Agreed on both counts.  The goal is to connect members with meetings.  I'll ping Steve and see what he suggests.
