### ISSUE TITLE
Can i submit a French translation file

### ISSUE THREAD

**Issue by Pascall50** [bmlt-enabled/BMLTSearch3#64]
[fr.json](https://github.com/bmlt-enabled/BMLTSearch3/files/15169357/fr.json)

**Comment by pjaudiomv** [comment]
You should be able to see translation here https://bmltsearch.bmlt.app, please take a look and make sure it looks good.

**Comment by Pascall50** [comment]
All is looking great!!

**Comment by paulnagle** [comment]
This will be in the next version of the app 5.3.2
